export const styleConstants = {
  button_background: '#785BFA',
  light_text: 'white',
  dark_text: '#1D1D1F',
  blue_text: '#785BFA',
  background_color: '#550096',
  base_background: '#F2F2F2',
  light_background: '#FFFFFF',
  subhead_text: '#8F9090',
  input_background: '#FFFFFF',
  input_color: '#8F9090',
  table_border: '#b690d4',
  success_color: 'seagreen',
  error_color: 'orangered',
  progress_color: 'aqua',
  card_primary: '#FFFFFF',
  card_secondary: '#3268F5',
  card_sleep: '#785BFA',
  icon_color: '#708090',
};
